### ISSUE TITLE
is crashing

### ISSUE THREAD

**Issue by Arvidon123** [0x4e49434f4c45/noteblock-assistant#1]
maybe am dumb but when i select its just closed the game how do i even get songs

**Comment by 0x4e49434f4c45** [comment]
Wait, people are actually using this thing? Amazing...

What Minecraft version are you on? I don't test this to anywhere near the extent I do my other mod, so it might just be a compatibility problem.

**Comment by 0x4e49434f4c45** [comment]
I was able to reproduce a crash on 1.21.3. Assuming that's this issue, it's fixed in [version 0.1.1](https://github.com/0x4e49434f4c45/noteblock-assistant/releases/tag/0.1.1), which updates to support Minecraft 1.21.2+.
